package util;

import java.awt.Image;

import junit.framework.TestCase;

// JUnitDoclet end import

/**
 * Generated by JUnitDoclet, a tool provided by ObjectFab GmbH under LGPL.
 * Please see www.junitdoclet.org, www.gnu.org and www.objectfab.de for
 * informations about the tool, the licence and the authors.
 */

public class ImageToolkitTest
// JUnitDoclet begin extends_implements
        extends TestCase
// JUnitDoclet end extends_implements
{
    // JUnitDoclet begin class
    util.ImageToolkit imagetoolkit = null;

    // JUnitDoclet end class

    public ImageToolkitTest(String name) {
        // JUnitDoclet begin method ImageToolkitTest
        super(name);
        // JUnitDoclet end method ImageToolkitTest
    }

    public util.ImageToolkit createInstance() throws Exception {
        // JUnitDoclet begin method testcase.createInstance
        return new util.ImageToolkit();
        // JUnitDoclet end method testcase.createInstance
    }

    protected void setUp() throws Exception {
        // JUnitDoclet begin method testcase.setUp
        super.setUp();
        imagetoolkit = createInstance();
        // JUnitDoclet end method testcase.setUp
    }

    protected void tearDown() throws Exception {
        // JUnitDoclet begin method testcase.tearDown
        imagetoolkit = null;
        super.tearDown();
        // JUnitDoclet end method testcase.tearDown
    }

    public void testLoadClasspathImage() throws Exception {
        // JUnitDoclet begin method loadClasspathImage
        Image image = ImageToolkit.loadClasspathImage("/current_min.jpg");
        assertNotNull(image);
        // JUnitDoclet end method loadClasspathImage
    }

    public void testLoadImage() throws Exception {
    // JUnitDoclet begin method loadImage
    // JUnitDoclet end method loadImage
    }

    public void testCreateImage() throws Exception {
    // JUnitDoclet begin method createImage
    // JUnitDoclet end method createImage
    }

    public void testMain() throws Exception {
    // JUnitDoclet begin method main
    // JUnitDoclet end method main
    }

    /**
     * JUnitDoclet moves marker to this method, if there is not match for them
     * in the regenerated code and if the marker is not empty. This way, no test
     * gets lost when regenerating after renaming. Method testVault is supposed
     * to be empty.
     */
    public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
    }

    public static void main(String[] args) {
        // JUnitDoclet begin method testcase.main
        junit.textui.TestRunner.run(ImageToolkitTest.class);
        // JUnitDoclet end method testcase.main
    }
}
