package util;

import junit.framework.TestCase;

// JUnitDoclet begin import
// JUnitDoclet end import

/**
 * Generated by JUnitDoclet, a tool provided by ObjectFab GmbH under LGPL.
 * Please see www.junitdoclet.org, www.gnu.org and www.objectfab.de for
 * informations about the tool, the licence and the authors.
 */

public class StringToolkitTest
// JUnitDoclet begin extends_implements
        extends TestCase
// JUnitDoclet end extends_implements
{
    // JUnitDoclet begin class
    util.StringToolkit stringtoolkit = null;

    // JUnitDoclet end class

    public StringToolkitTest(String name) {
        // JUnitDoclet begin method StringToolkitTest
        super(name);
        // JUnitDoclet end method StringToolkitTest
    }

    public util.StringToolkit createInstance() throws Exception {
        // JUnitDoclet begin method testcase.createInstance
        return new util.StringToolkit();
        // JUnitDoclet end method testcase.createInstance
    }

    protected void setUp() throws Exception {
        // JUnitDoclet begin method testcase.setUp
        super.setUp();
        stringtoolkit = createInstance();
        // JUnitDoclet end method testcase.setUp
    }

    protected void tearDown() throws Exception {
        // JUnitDoclet begin method testcase.tearDown
        stringtoolkit = null;
        super.tearDown();
        // JUnitDoclet end method testcase.tearDown
    }

    public void testGetSubStringCount() throws Exception {
    // JUnitDoclet begin method getSubStringCount
    // JUnitDoclet end method getSubStringCount
    }

    public void testRepeatString() throws Exception {
    // JUnitDoclet begin method repeatString
    // JUnitDoclet end method repeatString
    }

    public void testReplaceSubString() throws Exception {
    // JUnitDoclet begin method replaceSubString
    // JUnitDoclet end method replaceSubString
    }

    public void testPadString() throws Exception {
    // JUnitDoclet begin method padString
    // JUnitDoclet end method padString
    }

    public void testParseString() throws Exception {
    // JUnitDoclet begin method parseString
    // JUnitDoclet end method parseString
    }

    public void testMain() throws Exception {
    // JUnitDoclet begin method main
    // JUnitDoclet end method main
    }

    /**
     * JUnitDoclet moves marker to this method, if there is not match for them
     * in the regenerated code and if the marker is not empty. This way, no test
     * gets lost when regenerating after renaming. Method testVault is supposed
     * to be empty.
     */
    public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
    }

    public static void main(String[] args) {
        // JUnitDoclet begin method testcase.main
        junit.textui.TestRunner.run(StringToolkitTest.class);
        // JUnitDoclet end method testcase.main
    }
}
