package metrics.splitters;

import junit.framework.TestCase;
import media.image.CloudImage;
import metrics.splitters.MaxMedianMetric;
import metrics.splitters.SplitterMetric;
// JUnitDoclet end import

/**
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/


public class MaxMedianMetricTest
// JUnitDoclet begin extends_implements
extends TestCase
// JUnitDoclet end extends_implements
{
  // JUnitDoclet begin class
  metrics.splitters.SplitterMetric maxmedianmetric = null;
  // JUnitDoclet end class
  
  public MaxMedianMetricTest(String name) {
    // JUnitDoclet begin method MaxMedianMetricTest
    super(name);
    // JUnitDoclet end method MaxMedianMetricTest
  }
  
  public metrics.splitters.MaxMedianMetric createInstance() throws Exception {
    // JUnitDoclet begin method testcase.createInstance
    return new metrics.splitters.MaxMedianMetric();
    // JUnitDoclet end method testcase.createInstance
  }
  
  protected void setUp() throws Exception {
    // JUnitDoclet begin method testcase.setUp
    super.setUp();
    maxmedianmetric = createInstance();
    // JUnitDoclet end method testcase.setUp
  }
  
  public void testMaxMedian() {
	  double[] data = { 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20 };
	     SplitterMetric metric = new MaxMedianMetric();
	     CloudImage image = new CloudImage(data, 5, 4);
	     assertEquals(0.0, metric.compute(image), 0.0);
  }
  
  protected void tearDown() throws Exception {
    // JUnitDoclet begin method testcase.tearDown
    maxmedianmetric = null;
    super.tearDown();
    // JUnitDoclet end method testcase.tearDown
  }
  
  
  
  /**
  * JUnitDoclet moves marker to this method, if there is not match
  * for them in the regenerated code and if the marker is not empty.
  * This way, no test gets lost when regenerating after renaming.
  * Method testVault is supposed to be empty.
  */
  public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault

    // JUnitDoclet end method testcase.testVault
  }
  
  public static void main(String[] args) {
    // JUnitDoclet begin method testcase.main
    junit.textui.TestRunner.run(MaxMedianMetricTest.class);
    // JUnitDoclet end method testcase.main
  }
}
