package metrics;

import calculation.CutoffDifferenceMetric;
import junit.framework.TestCase;
// JUnitDoclet begin import
// JUnitDoclet end import

/**
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/


public class CutoffDifferenceMetricTest
// JUnitDoclet begin extends_implements
extends TestCase
// JUnitDoclet end extends_implements
{
  // JUnitDoclet begin class
  calculation.CutoffDifferenceMetric cutoffdifferencemetric = null;
  // JUnitDoclet end class
  
  public CutoffDifferenceMetricTest(String name) {
    // JUnitDoclet begin method CutoffDifferenceMetricTest
    super(name);
    // JUnitDoclet end method CutoffDifferenceMetricTest
  }
  
  public calculation.CutoffDifferenceMetric createInstance() throws Exception {
    // JUnitDoclet begin method testcase.createInstance
    return new calculation.CutoffDifferenceMetric();
    // JUnitDoclet end method testcase.createInstance
  }
  
  protected void setUp() throws Exception {
    // JUnitDoclet begin method testcase.setUp
    super.setUp();
    cutoffdifferencemetric = createInstance();
    // JUnitDoclet end method testcase.setUp
  }
  
  protected void tearDown() throws Exception {
    // JUnitDoclet begin method testcase.tearDown
    cutoffdifferencemetric = null;
    super.tearDown();
    // JUnitDoclet end method testcase.tearDown
  }
  
  public void testCompute() throws Exception {
    // JUnitDoclet begin method compute
    // JUnitDoclet end method compute
  }
  
  public void testSetWidth() throws Exception {
    // JUnitDoclet begin method setWidth
    // JUnitDoclet end method setWidth
  }
  
  
  
  /**
  * JUnitDoclet moves marker to this method, if there is not match
  * for them in the regenerated code and if the marker is not empty.
  * This way, no test gets lost when regenerating after renaming.
  * Method testVault is supposed to be empty.
  */
  public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
  }
  
  public static void main(String[] args) {
    // JUnitDoclet begin method testcase.main
    junit.textui.TestRunner.run(CutoffDifferenceMetricTest.class);
    // JUnitDoclet end method testcase.main
  }
}
