package metrics;

import junit.framework.TestCase;
// JUnitDoclet begin import
import media.image.CloudImage;
import metrics.LineMedianDifferenceMetric;
import metrics.splitters.MaxMedianSplitterMetric;
import metrics.splitters.SplitterMetric;

// JUnitDoclet end import

/**
 * Generated by JUnitDoclet, a tool provided by ObjectFab GmbH under LGPL.
 * Please see www.junitdoclet.org, www.gnu.org and www.objectfab.de for
 * informations about the tool, the licence and the authors.
 */

public class LineMedianDifferenceMetricTest
// JUnitDoclet begin extends_implements
        extends TestCase
// JUnitDoclet end extends_implements
{
    // JUnitDoclet begin class
    metrics.LineMedianDifferenceMetric linemediandifferencemetric = null;

    // JUnitDoclet end class

    public LineMedianDifferenceMetricTest(String name) {
        // JUnitDoclet begin method LineMedianDifferenceMetricTest
        super(name);
        // JUnitDoclet end method LineMedianDifferenceMetricTest
    }

    public metrics.LineMedianDifferenceMetric createInstance() throws Exception {
        // JUnitDoclet begin method testcase.createInstance
        return new metrics.LineMedianDifferenceMetric();
        // JUnitDoclet end method testcase.createInstance
    }

    protected void setUp() throws Exception {
        // JUnitDoclet begin method testcase.setUp
        super.setUp();
        linemediandifferencemetric = createInstance();
        // JUnitDoclet end method testcase.setUp
    }

    protected void tearDown() throws Exception {
        // JUnitDoclet begin method testcase.tearDown
        linemediandifferencemetric = null;
        super.tearDown();
        // JUnitDoclet end method testcase.tearDown
    }

    public void testCompute() throws Exception {
        // JUnitDoclet begin method compute
        int[] data = { 0, 0, 0, 0, 0, 0, 0, 0, 50, 50, 50, 50, 100, 100, 100, 100, 100, 100,
                100, 100 };
        Metric metric = new LineMedianDifferenceMetric();
        CloudImage image = new CloudImage(data, 4, 5);
        assertEquals(100.0, metric.compute(image), 0.0);
        // JUnitDoclet end method compute
    }

    public void testSetWidth() throws Exception {
    // JUnitDoclet begin method setWidth
    // JUnitDoclet end method setWidth
    }

    /**
     * JUnitDoclet moves marker to this method, if there is not match for them
     * in the regenerated code and if the marker is not empty. This way, no test
     * gets lost when regenerating after renaming. Method testVault is supposed
     * to be empty.
     */
    public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
    }

    public static void main(String[] args) {
        // JUnitDoclet begin method testcase.main
        junit.textui.TestRunner.run(LineMedianDifferenceMetricTest.class);
        // JUnitDoclet end method testcase.main
    }
}
