package metrics;

import junit.framework.TestSuite;


// JUnitDoclet begin import
// JUnitDoclet end import

/**
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/


public class MetricsSuite
// JUnitDoclet begin extends_implements
// JUnitDoclet end extends_implements
{
  // JUnitDoclet begin class
  // JUnitDoclet end class
  
  public static TestSuite suite() {
    
    TestSuite suite;
    
    suite = new TestSuite("metrics");
    
    suite.addTestSuite(metrics.StdDevMetricTest.class);
    suite.addTestSuite(metrics.splitters.SlidingWindowSplitterTest.class);
    suite.addTestSuite(metrics.PixelBrightnessMetricTest.class);
    suite.addTestSuite(metrics.splitters.MaxStdDevMetricTest.class);
    suite.addTestSuite(metrics.splitters.MaxMedianMetricTest.class);
    suite.addTestSuite(metrics.LineMedianDifferenceMetricTest.class);
    suite.addTestSuite(metrics.KMeansMetricTest.class);
    suite.addTestSuite(metrics.CutoffDifferenceMetricTest.class);
    
    
    
    // JUnitDoclet begin method suite
    // JUnitDoclet end method suite
    
    return suite;
  }
  
  public static void main(String[] args) {
    // JUnitDoclet begin method testsuite.main
    junit.textui.TestRunner.run(suite());
    // JUnitDoclet end method testsuite.main
  }
}
