package ui.commands;

import junit.framework.TestCase;

// JUnitDoclet begin import
// JUnitDoclet end import

/**
 * Generated by JUnitDoclet, a tool provided by ObjectFab GmbH under LGPL.
 * Please see www.junitdoclet.org, www.gnu.org and www.objectfab.de for
 * informations about the tool, the licence and the authors.
 */

public class StatusCommandTest
// JUnitDoclet begin extends_implements
        extends TestCase
// JUnitDoclet end extends_implements
{
    // JUnitDoclet begin class
    ui.commands.StatusCommand statuscommand = null;

    // JUnitDoclet end class

    public StatusCommandTest(String name) {
        // JUnitDoclet begin method StatusCommandTest
        super(name);
        // JUnitDoclet end method StatusCommandTest
    }

    public ui.commands.StatusCommand createInstance() throws Exception {
        // JUnitDoclet begin method testcase.createInstance
        return new ui.commands.StatusCommand();
        // JUnitDoclet end method testcase.createInstance
    }

    protected void setUp() throws Exception {
        // JUnitDoclet begin method testcase.setUp
        super.setUp();
        statuscommand = createInstance();
        // JUnitDoclet end method testcase.setUp
    }

    protected void tearDown() throws Exception {
        // JUnitDoclet begin method testcase.tearDown
        statuscommand = null;
        super.tearDown();
        // JUnitDoclet end method testcase.tearDown
    }

    public void testExecute() throws Exception {
    // JUnitDoclet begin method execute
    // JUnitDoclet end method execute
    }

    /**
     * JUnitDoclet moves marker to this method, if there is not match for them
     * in the regenerated code and if the marker is not empty. This way, no test
     * gets lost when regenerating after renaming. Method testVault is supposed
     * to be empty.
     */
    public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
    }

    public static void main(String[] args) {
        // JUnitDoclet begin method testcase.main
        junit.textui.TestRunner.run(StatusCommandTest.class);
        // JUnitDoclet end method testcase.main
    }
}
