package ui;

import junit.framework.TestCase;

// JUnitDoclet end import

/**
 * Generated by JUnitDoclet, a tool provided by ObjectFab GmbH under LGPL.
 * Please see www.junitdoclet.org, www.gnu.org and www.objectfab.de for
 * informations about the tool, the licence and the authors.
 */

public class ImageFrameTest
// JUnitDoclet begin extends_implements
        extends TestCase
// JUnitDoclet end extends_implements
{
    // JUnitDoclet begin class
    util.ImagePanel imageframe = null;

    // JUnitDoclet end class

    public ImageFrameTest(String name) {
        // JUnitDoclet begin method ImageFrameTest
        super(name);
        // JUnitDoclet end method ImageFrameTest
    }

    public util.ImagePanel createInstance() throws Exception {
        // JUnitDoclet begin method testcase.createInstance
        return null;// new ui.ImagePanel("");
        // JUnitDoclet end method testcase.createInstance
    }

    protected void setUp() throws Exception {
        // JUnitDoclet begin method testcase.setUp
        super.setUp();
        imageframe = createInstance();
        // JUnitDoclet end method testcase.setUp
    }

    protected void tearDown() throws Exception {
        // JUnitDoclet begin method testcase.tearDown
        imageframe = null;
        super.tearDown();
        // JUnitDoclet end method testcase.tearDown
    }

    public void testPaint() throws Exception {
    // JUnitDoclet begin method paint
    // JUnitDoclet end method paint
    }

    public void testMain() throws Exception {
    // JUnitDoclet begin method main
    // JUnitDoclet end method main
    }

    public void testSetGetImage() throws Exception {
    // JUnitDoclet begin method setImage getImage
    // java.awt.Image[] tests = {new java.awt.Image(), null};
    //    
    // for (int i = 0; i < tests.length; i++) {
    // imageframe.setImage(tests[i]);
    // assertEquals(tests[i], imageframe.getImage());
    // }
    // JUnitDoclet end method setImage getImage
    }

    /**
     * JUnitDoclet moves marker to this method, if there is not match for them
     * in the regenerated code and if the marker is not empty. This way, no test
     * gets lost when regenerating after renaming. Method testVault is supposed
     * to be empty.
     */
    public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
    }

    public static void main(String[] args) {
        // JUnitDoclet begin method testcase.main
        junit.textui.TestRunner.run(ImageFrameTest.class);
        // JUnitDoclet end method testcase.main
    }
}
