package util;

import javax.media.format.RGBFormat;

import media.image.RGBImageStacker;


import junit.framework.TestCase;
// JUnitDoclet begin import
// JUnitDoclet end import

/**
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/


public class ImageStackerTest
// JUnitDoclet begin extends_implements
extends TestCase
// JUnitDoclet end extends_implements
{
  // JUnitDoclet begin class
  media.image.RGBImageStacker imagestacker = null;
  // JUnitDoclet end class
  
  public ImageStackerTest(String name) {
    // JUnitDoclet begin method ImageStackerTest
    super(name);
    // JUnitDoclet end method ImageStackerTest
  }
  
  public media.image.RGBImageStacker createInstance() throws Exception {
    // JUnitDoclet begin method testcase.createInstance
    return new media.image.RGBImageStacker(new RGBFormat());
    // JUnitDoclet end method testcase.createInstance
  }
  
  protected void setUp() throws Exception {
    // JUnitDoclet begin method testcase.setUp
    super.setUp();
    imagestacker = createInstance();
    // JUnitDoclet end method testcase.setUp
  }
  
  protected void tearDown() throws Exception {
    // JUnitDoclet begin method testcase.tearDown
    imagestacker = null;
    super.tearDown();
    // JUnitDoclet end method testcase.tearDown
  }
  
  public void testStackData() throws Exception {
    // JUnitDoclet begin method stackData
    // JUnitDoclet end method stackData
  }
  
  public void testGetOriginalStackData() throws Exception {
    // JUnitDoclet begin method getOriginalStackData
    // JUnitDoclet end method getOriginalStackData
  }
  
  public void testGetProcessedStackData() throws Exception {
    // JUnitDoclet begin method getProcessedStackData
    // JUnitDoclet end method getProcessedStackData
  }
  
  public void testIsStacked() throws Exception {
    // JUnitDoclet begin method isStacked
    // JUnitDoclet end method isStacked
  }
  
  
  
  /**
  * JUnitDoclet moves marker to this method, if there is not match
  * for them in the regenerated code and if the marker is not empty.
  * This way, no test gets lost when regenerating after renaming.
  * Method testVault is supposed to be empty.
  */
  public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
  }
  
  public static void main(String[] args) {
    // JUnitDoclet begin method testcase.main
    junit.textui.TestRunner.run(ImageStackerTest.class);
    // JUnitDoclet end method testcase.main
  }
}
