package util;

import junit.framework.TestCase;
// JUnitDoclet begin import
import util.SoundUtil;
// JUnitDoclet end import

/**
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/


public class SoundUtilTest
// JUnitDoclet begin extends_implements
extends TestCase
// JUnitDoclet end extends_implements
{
  // JUnitDoclet begin class
  SoundUtil soundutil = null;
  // JUnitDoclet end class
  
  public SoundUtilTest(String name) {
    // JUnitDoclet begin method SoundUtilTest
    super(name);
    // JUnitDoclet end method SoundUtilTest
  }
  
  public util.SoundUtil createInstance() throws Exception {
    // JUnitDoclet begin method testcase.createInstance
    return new util.SoundUtil();
    // JUnitDoclet end method testcase.createInstance
  }
  
  protected void setUp() throws Exception {
    // JUnitDoclet begin method testcase.setUp
    super.setUp();
    soundutil = createInstance();
    // JUnitDoclet end method testcase.setUp
  }
  
  protected void tearDown() throws Exception {
    // JUnitDoclet begin method testcase.tearDown
    soundutil = null;
    super.tearDown();
    // JUnitDoclet end method testcase.tearDown
  }
  
  public void testPlay() throws Exception {
    // JUnitDoclet begin method play
    // JUnitDoclet end method play
  }
  
  public void testUpdate() throws Exception {
    // JUnitDoclet begin method update
    // JUnitDoclet end method update
  }
  
  
  
  /**
  * JUnitDoclet moves marker to this method, if there is not match
  * for them in the regenerated code and if the marker is not empty.
  * This way, no test gets lost when regenerating after renaming.
  * Method testVault is supposed to be empty.
  */
  public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
  }
  
  public static void main(String[] args) {
    // JUnitDoclet begin method testcase.main
    junit.textui.TestRunner.run(SoundUtilTest.class);
    // JUnitDoclet end method testcase.main
  }
}
