package util;

import junit.framework.TestCase;
// JUnitDoclet begin import
import util.TextProgressBar;
// JUnitDoclet end import

/**
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/


public class TextProgressBarTest
// JUnitDoclet begin extends_implements
extends TestCase
// JUnitDoclet end extends_implements
{
  // JUnitDoclet begin class
  util.TextProgressBar textprogressbar = null;
  // JUnitDoclet end class
  
  public TextProgressBarTest(String name) {
    // JUnitDoclet begin method TextProgressBarTest
    super(name);
    // JUnitDoclet end method TextProgressBarTest
  }
  
  public util.TextProgressBar createInstance() throws Exception {
    // JUnitDoclet begin method testcase.createInstance
    return new util.TextProgressBar();
    // JUnitDoclet end method testcase.createInstance
  }
  
  protected void setUp() throws Exception {
    // JUnitDoclet begin method testcase.setUp
    super.setUp();
    textprogressbar = createInstance();
    // JUnitDoclet end method testcase.setUp
  }
  
  protected void tearDown() throws Exception {
    // JUnitDoclet begin method testcase.tearDown
    textprogressbar = null;
    super.tearDown();
    // JUnitDoclet end method testcase.tearDown
  }
  
  public void testUpdate() throws Exception {
    // JUnitDoclet begin method update
    // JUnitDoclet end method update
  }
  
  public void testSetScalingParameters() throws Exception {
    // JUnitDoclet begin method setScalingParameters
    // JUnitDoclet end method setScalingParameters
  }
  
  public void testPrint() throws Exception {
    // JUnitDoclet begin method print
    // JUnitDoclet end method print
  }
  
  
  
  /**
  * JUnitDoclet moves marker to this method, if there is not match
  * for them in the regenerated code and if the marker is not empty.
  * This way, no test gets lost when regenerating after renaming.
  * Method testVault is supposed to be empty.
  */
  public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
  }
  
  public static void main(String[] args) {
    // JUnitDoclet begin method testcase.main
    junit.textui.TestRunner.run(TextProgressBarTest.class);
    // JUnitDoclet end method testcase.main
  }
}
