package ui;

import junit.framework.TestCase;
// JUnitDoclet begin import
import ui.AxisCharts;
// JUnitDoclet end import

/**
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/


public class AxisChartsTest
// JUnitDoclet begin extends_implements
extends TestCase
// JUnitDoclet end extends_implements
{
  // JUnitDoclet begin class
  ui.AxisCharts axischarts = null;
  // JUnitDoclet end class
  
  public AxisChartsTest(String name) {
    // JUnitDoclet begin method AxisChartsTest
    super(name);
    // JUnitDoclet end method AxisChartsTest
  }
  
  public ui.AxisCharts createInstance() throws Exception {
    // JUnitDoclet begin method testcase.createInstance
    return new ui.AxisCharts();
    // JUnitDoclet end method testcase.createInstance
  }
  
  protected void setUp() throws Exception {
    // JUnitDoclet begin method testcase.setUp
    super.setUp();
    axischarts = createInstance();
    // JUnitDoclet end method testcase.setUp
  }
  
  protected void tearDown() throws Exception {
    // JUnitDoclet begin method testcase.tearDown
    axischarts = null;
    super.tearDown();
    // JUnitDoclet end method testcase.tearDown
  }
  
  public void testRun() throws Exception {
    // JUnitDoclet begin method run
    // JUnitDoclet end method run
  }
  
  public void testCreateDataSeries() throws Exception {
    // JUnitDoclet begin method createDataSeries
    // JUnitDoclet end method createDataSeries
  }
  
  public void testCreateAxisChartDataSet() throws Exception {
    // JUnitDoclet begin method createAxisChartDataSet
    // JUnitDoclet end method createAxisChartDataSet
  }
  
  
  
  /**
  * JUnitDoclet moves marker to this method, if there is not match
  * for them in the regenerated code and if the marker is not empty.
  * This way, no test gets lost when regenerating after renaming.
  * Method testVault is supposed to be empty.
  */
  public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
  }
  
  public static void main(String[] args) {
    // JUnitDoclet begin method testcase.main
    junit.textui.TestRunner.run(AxisChartsTest.class);
    // JUnitDoclet end method testcase.main
  }
}
