package ui;

import junit.framework.TestCase;
// JUnitDoclet begin import
import ui.CloudWatchFrame;
// JUnitDoclet end import

/**
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/


public class CloudWatchFrameTest
// JUnitDoclet begin extends_implements
extends TestCase
// JUnitDoclet end extends_implements
{
  // JUnitDoclet begin class
  ui.CloudWatchFrame cloudwatchframe = null;
  // JUnitDoclet end class
  
  public CloudWatchFrameTest(String name) {
    // JUnitDoclet begin method CloudWatchFrameTest
    super(name);
    // JUnitDoclet end method CloudWatchFrameTest
  }
  
  public ui.CloudWatchFrame createInstance() throws Exception {
    // JUnitDoclet begin method testcase.createInstance
    return new ui.CloudWatchFrame();
    // JUnitDoclet end method testcase.createInstance
  }
  
  protected void setUp() throws Exception {
    // JUnitDoclet begin method testcase.setUp
    super.setUp();
    cloudwatchframe = createInstance();
    // JUnitDoclet end method testcase.setUp
  }
  
  protected void tearDown() throws Exception {
    // JUnitDoclet begin method testcase.tearDown
    cloudwatchframe = null;
    super.tearDown();
    // JUnitDoclet end method testcase.tearDown
  }
  
  public void testMain() throws Exception {
    // JUnitDoclet begin method main
    // JUnitDoclet end method main
  }
  
  public void testGetContrastChart() throws Exception {
    // JUnitDoclet begin method getContrastChart
    // JUnitDoclet end method getContrastChart
  }
  
  
  
  /**
  * JUnitDoclet moves marker to this method, if there is not match
  * for them in the regenerated code and if the marker is not empty.
  * This way, no test gets lost when regenerating after renaming.
  * Method testVault is supposed to be empty.
  */
  public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
  }
  
  public static void main(String[] args) {
    // JUnitDoclet begin method testcase.main
    junit.textui.TestRunner.run(CloudWatchFrameTest.class);
    // JUnitDoclet end method testcase.main
  }
}
