package media.jmf;

import junit.framework.TestCase;
// JUnitDoclet begin import
import media.jmf.JMFSettings;
// JUnitDoclet end import

/**
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/


public class JMFSettingsTest
// JUnitDoclet begin extends_implements
extends TestCase
// JUnitDoclet end extends_implements
{
  // JUnitDoclet begin class
  media.jmf.JMFSettings jmfsettings = null;
  // JUnitDoclet end class
  
  public JMFSettingsTest(String name) {
    // JUnitDoclet begin method JMFSettingsTest
    super(name);
    // JUnitDoclet end method JMFSettingsTest
  }
  
  public media.jmf.JMFSettings createInstance() throws Exception {
    // JUnitDoclet begin method testcase.createInstance
    return new media.jmf.JMFSettings();
    // JUnitDoclet end method testcase.createInstance
  }
  
  protected void setUp() throws Exception {
    // JUnitDoclet begin method testcase.setUp
    super.setUp();
    jmfsettings = createInstance();
    // JUnitDoclet end method testcase.setUp
  }
  
  protected void tearDown() throws Exception {
    // JUnitDoclet begin method testcase.tearDown
    jmfsettings = null;
    super.tearDown();
    // JUnitDoclet end method testcase.tearDown
  }
  
  public void testIsWebcamDetected() throws Exception {
    // JUnitDoclet begin method isWebcamDetected
    // JUnitDoclet end method isWebcamDetected
  }
  
  public void testGetWebcams() throws Exception {
    // JUnitDoclet begin method getWebcams
    // JUnitDoclet end method getWebcams
  }
  
  public void testGetWebcamInfo() throws Exception {
    // JUnitDoclet begin method getWebcamInfo
    // JUnitDoclet end method getWebcamInfo
  }
  
  public void testMain() throws Exception {
    // JUnitDoclet begin method main
    // JUnitDoclet end method main
  }
  
  
  
  /**
  * JUnitDoclet moves marker to this method, if there is not match
  * for them in the regenerated code and if the marker is not empty.
  * This way, no test gets lost when regenerating after renaming.
  * Method testVault is supposed to be empty.
  */
  public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
  }
  
  public static void main(String[] args) {
    // JUnitDoclet begin method testcase.main
    junit.textui.TestRunner.run(JMFSettingsTest.class);
    // JUnitDoclet end method testcase.main
  }
}
