package media.web;

import junit.framework.TestCase;

// JUnitDoclet begin import
// JUnitDoclet end import

/**
 * Generated by JUnitDoclet, a tool provided by ObjectFab GmbH under LGPL.
 * Please see www.junitdoclet.org, www.gnu.org and www.objectfab.de for
 * informations about the tool, the licence and the authors.
 */

public class WebLoaderTest
// JUnitDoclet begin extends_implements
        extends TestCase
// JUnitDoclet end extends_implements
{
    // JUnitDoclet begin class
    media.web.WebLoader webLoader = null;

    // JUnitDoclet end class

    public WebLoaderTest(String name) {
        // JUnitDoclet begin method WebImageLoaderTest
        super(name);
        // JUnitDoclet end method WebImageLoaderTest
    }

    public media.web.WebLoader createInstance() throws Exception {
        // JUnitDoclet begin method testcase.createInstance
        return new media.web.WebLoader();
        // JUnitDoclet end method testcase.createInstance
    }

    protected void setUp() throws Exception {
        // JUnitDoclet begin method testcase.setUp
        super.setUp();
        webLoader = createInstance();
        // JUnitDoclet end method testcase.setUp
    }

    protected void tearDown() throws Exception {
        // JUnitDoclet begin method testcase.tearDown
        webLoader = null;
        super.tearDown();
        // JUnitDoclet end method testcase.tearDown
    }

    public void testLoadURLImage() throws Exception {
    // JUnitDoclet begin method loadURLImage
    // JUnitDoclet end method loadURLImage
    }
    
    public void testLoadURLFile() throws Exception {
    
    	String result = webLoader.loadURLFile("http://mira.telenet.be/wolkensensor/Aag_ccdap4.dat"); 
    	assertNotNull(result);
    }

    

    public void testMain() throws Exception {
    // JUnitDoclet begin method main
    // JUnitDoclet end method main
    }

    /**
     * JUnitDoclet moves marker to this method, if there is not match for them
     * in the regenerated code and if the marker is not empty. This way, no test
     * gets lost when regenerating after renaming. Method testVault is supposed
     * to be empty.
     */
    public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
    }

    public static void main(String[] args) {
        // JUnitDoclet begin method testcase.main
        junit.textui.TestRunner.run(WebLoaderTest.class);
        // JUnitDoclet end method testcase.main
    }
}
