package ui.commands;

import junit.framework.TestCase;
// JUnitDoclet begin import
import ui.commands.ImageCommand;
// JUnitDoclet end import

/**
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/


public class ImageCommandTest
// JUnitDoclet begin extends_implements
extends TestCase
// JUnitDoclet end extends_implements
{
  // JUnitDoclet begin class
  ui.commands.ImageCommand imagecommand = null;
  // JUnitDoclet end class
  
  public ImageCommandTest(String name) {
    // JUnitDoclet begin method ImageCommandTest
    super(name);
    // JUnitDoclet end method ImageCommandTest
  }
  
  public ui.commands.ImageCommand createInstance() throws Exception {
    // JUnitDoclet begin method testcase.createInstance
    return new ui.commands.ImageCommand(null);
    // JUnitDoclet end method testcase.createInstance
  }
  
  protected void setUp() throws Exception {
    // JUnitDoclet begin method testcase.setUp
    super.setUp();
    imagecommand = createInstance();
    // JUnitDoclet end method testcase.setUp
  }
  
  protected void tearDown() throws Exception {
    // JUnitDoclet begin method testcase.tearDown
    imagecommand = null;
    super.tearDown();
    // JUnitDoclet end method testcase.tearDown
  }
  
  public void testExecute() throws Exception {
    // JUnitDoclet begin method execute
    // JUnitDoclet end method execute
  }
  
  
  
  /**
  * JUnitDoclet moves marker to this method, if there is not match
  * for them in the regenerated code and if the marker is not empty.
  * This way, no test gets lost when regenerating after renaming.
  * Method testVault is supposed to be empty.
  */
  public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
  }
  
  public static void main(String[] args) {
    // JUnitDoclet begin method testcase.main
    junit.textui.TestRunner.run(ImageCommandTest.class);
    // JUnitDoclet end method testcase.main
  }
}
