package application;

import junit.framework.TestCase;
// JUnitDoclet begin import
import application.CloudFrame;
// JUnitDoclet end import

/**
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/


public class CloudFrameTest
// JUnitDoclet begin extends_implements
extends TestCase
// JUnitDoclet end extends_implements
{
  // JUnitDoclet begin class
  application.CloudFrame cloudframe = null;
  // JUnitDoclet end class
  
  public CloudFrameTest(String name) {
    // JUnitDoclet begin method CloudFrameTest
    super(name);
    // JUnitDoclet end method CloudFrameTest
  }
  
  public application.CloudFrame createInstance() throws Exception {
    // JUnitDoclet begin method testcase.createInstance
    return new application.CloudFrame();
    // JUnitDoclet end method testcase.createInstance
  }
  
  protected void setUp() throws Exception {
    // JUnitDoclet begin method testcase.setUp
    super.setUp();
    cloudframe = createInstance();
    // JUnitDoclet end method testcase.setUp
  }
  
  protected void tearDown() throws Exception {
    // JUnitDoclet begin method testcase.tearDown
    cloudframe = null;
    super.tearDown();
    // JUnitDoclet end method testcase.tearDown
  }
  
  public void testOpen() throws Exception {
    // JUnitDoclet begin method open
    // JUnitDoclet end method open
  }
  
  public void testAddNotify() throws Exception {
    // JUnitDoclet begin method addNotify
    // JUnitDoclet end method addNotify
  }
  
  public void testControllerUpdate() throws Exception {
    // JUnitDoclet begin method controllerUpdate
    // JUnitDoclet end method controllerUpdate
  }
  
  public void testMain() throws Exception {
    // JUnitDoclet begin method main
    // JUnitDoclet end method main
  }
  
  
  
  /**
  * JUnitDoclet moves marker to this method, if there is not match
  * for them in the regenerated code and if the marker is not empty.
  * This way, no test gets lost when regenerating after renaming.
  * Method testVault is supposed to be empty.
  */
  public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
  }
  
  public static void main(String[] args) {
    // JUnitDoclet begin method testcase.main
    junit.textui.TestRunner.run(CloudFrameTest.class);
    // JUnitDoclet end method testcase.main
  }
}
