package application;

import junit.framework.TestCase;
// JUnitDoclet end import

/**
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/


public class CloudWatchTest
// JUnitDoclet begin extends_implements
extends TestCase
// JUnitDoclet end extends_implements
{
  // JUnitDoclet begin class
  application.CloudWatch cloudwatch = null;
  // JUnitDoclet end class
  
  public CloudWatchTest(String name) {
    // JUnitDoclet begin method CloudWatchTest
    super(name);
    // JUnitDoclet end method CloudWatchTest
  }
  
  public application.CloudWatch createInstance() throws Exception {
    // JUnitDoclet begin method testcase.createInstance
    return new application.CloudWatch();
    // JUnitDoclet end method testcase.createInstance
  }
  
  protected void setUp() throws Exception {
    // JUnitDoclet begin method testcase.setUp
    super.setUp();
    cloudwatch = createInstance();
    // JUnitDoclet end method testcase.setUp
  }
  
  protected void tearDown() throws Exception {
    // JUnitDoclet begin method testcase.tearDown
    cloudwatch = null;
    super.tearDown();
    // JUnitDoclet end method testcase.tearDown
  }
  
  public void testProcessCommandLine() throws Exception {
    // JUnitDoclet begin method processCommandLine
  	CloudWatchConfig config;
  	String[] arg = { "bla", "-u", "-x"};
  	config = cloudwatch.processCommandLine(arg);
  	assertTrue(config.usesUI);
    // JUnitDoclet end method processCommandLine
  }
  
  public void testStartApplication() throws Exception {
    // JUnitDoclet begin method startApplication
    // JUnitDoclet end method startApplication
  }
  
  public void testMain() throws Exception {
    // JUnitDoclet begin method main
    // JUnitDoclet end method main
  }
  
  
  
  /**
  * JUnitDoclet moves marker to this method, if there is not match
  * for them in the regenerated code and if the marker is not empty.
  * This way, no test gets lost when regenerating after renaming.
  * Method testVault is supposed to be empty.
  */
  public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
  }
  
  public static void main(String[] args) {
    // JUnitDoclet begin method testcase.main
    junit.textui.TestRunner.run(CloudWatchTest.class);
    // JUnitDoclet end method testcase.main
  }
}
