package ui;

import junit.framework.TestCase;
// JUnitDoclet begin import
// JUnitDoclet end import

/**
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/


public class ContrastChartTest
// JUnitDoclet begin extends_implements
extends TestCase
// JUnitDoclet end extends_implements
{
  // JUnitDoclet begin class
  ui.ContrastChart contrastchart = null;
  // JUnitDoclet end class
  
  public ContrastChartTest(String name) {
    // JUnitDoclet begin method ContrastChartTest
    super(name);
    // JUnitDoclet end method ContrastChartTest
  }
  
  public ui.ContrastChart createInstance() throws Exception {
    // JUnitDoclet begin method testcase.createInstance
    return new ui.ContrastChart();
    // JUnitDoclet end method testcase.createInstance
  }
  
  protected void setUp() throws Exception {
    // JUnitDoclet begin method testcase.setUp
    super.setUp();
    contrastchart = createInstance();
    // JUnitDoclet end method testcase.setUp
  }
  
  protected void tearDown() throws Exception {
    // JUnitDoclet begin method testcase.tearDown
    contrastchart = null;
    super.tearDown();
    // JUnitDoclet end method testcase.tearDown
  }
  
  public void testGetJFreeChart() throws Exception {
    // JUnitDoclet begin method getJFreeChart
    // JUnitDoclet end method getJFreeChart
  }
  
  public void testAddValue() throws Exception {
    // JUnitDoclet begin method addValue
    // JUnitDoclet end method addValue
  }
  
  public void testGetChartPanel() throws Exception {
    // JUnitDoclet begin method getChartPanel
    // JUnitDoclet end method getChartPanel
  }
  
  
  
  /**
  * JUnitDoclet moves marker to this method, if there is not match
  * for them in the regenerated code and if the marker is not empty.
  * This way, no test gets lost when regenerating after renaming.
  * Method testVault is supposed to be empty.
  */
  public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
  }
  
  public static void main(String[] args) {
    // JUnitDoclet begin method testcase.main
    junit.textui.TestRunner.run(ContrastChartTest.class);
    // JUnitDoclet end method testcase.main
  }
}
