package media.jmf;

import junit.framework.TestCase;
// JUnitDoclet begin import
import media.jmf.DeviceInfo;
// JUnitDoclet end import

/**
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/


public class DeviceInfoTest
// JUnitDoclet begin extends_implements
extends TestCase
// JUnitDoclet end extends_implements
{
  // JUnitDoclet begin class
  media.jmf.DeviceInfo deviceinfo = null;
  // JUnitDoclet end class
  
  public DeviceInfoTest(String name) {
    // JUnitDoclet begin method DeviceInfoTest
    super(name);
    // JUnitDoclet end method DeviceInfoTest
  }
  
  public media.jmf.DeviceInfo createInstance() throws Exception {
    // JUnitDoclet begin method testcase.createInstance
    return new media.jmf.DeviceInfo();
    // JUnitDoclet end method testcase.createInstance
  }
  
  protected void setUp() throws Exception {
    // JUnitDoclet begin method testcase.setUp
    super.setUp();
    deviceinfo = createInstance();
    // JUnitDoclet end method testcase.setUp
  }
  
  protected void tearDown() throws Exception {
    // JUnitDoclet begin method testcase.tearDown
    deviceinfo = null;
    super.tearDown();
    // JUnitDoclet end method testcase.tearDown
  }
  
  public void testFormatMatches() throws Exception {
    // JUnitDoclet begin method formatMatches
    // JUnitDoclet end method formatMatches
  }
  
  public void testSetFormat() throws Exception {
    // JUnitDoclet begin method setFormat
    // JUnitDoclet end method setFormat
  }
  
  public void testIsVideo() throws Exception {
    // JUnitDoclet begin method isVideo
    // JUnitDoclet end method isVideo
  }
  
  public void testIsAudio() throws Exception {
    // JUnitDoclet begin method isAudio
    // JUnitDoclet end method isAudio
  }
  
  public void testFormatToString() throws Exception {
    // JUnitDoclet begin method formatToString
    // JUnitDoclet end method formatToString
  }
  
  public void testVideoFormatToString() throws Exception {
    // JUnitDoclet begin method videoFormatToString
    // JUnitDoclet end method videoFormatToString
  }
  
  public void testAudioFormatToString() throws Exception {
    // JUnitDoclet begin method audioFormatToString
    // JUnitDoclet end method audioFormatToString
  }
  
  
  
  /**
  * JUnitDoclet moves marker to this method, if there is not match
  * for them in the regenerated code and if the marker is not empty.
  * This way, no test gets lost when regenerating after renaming.
  * Method testVault is supposed to be empty.
  */
  public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
  }
  
  public static void main(String[] args) {
    // JUnitDoclet begin method testcase.main
    junit.textui.TestRunner.run(DeviceInfoTest.class);
    // JUnitDoclet end method testcase.main
  }
}
