package application;

import junit.framework.TestCase;
// JUnitDoclet begin import
import application.JMFInit;
// JUnitDoclet end import

/**
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/


public class JMFInitTest
// JUnitDoclet begin extends_implements
extends TestCase
// JUnitDoclet end extends_implements
{
  // JUnitDoclet begin class
  application.JMFInit jmfinit = null;
  // JUnitDoclet end class
  
  public JMFInitTest(String name) {
    // JUnitDoclet begin method JMFInitTest
    super(name);
    // JUnitDoclet end method JMFInitTest
  }
  
  public application.JMFInit createInstance() throws Exception {
    // JUnitDoclet begin method testcase.createInstance
    return new application.JMFInit();
    // JUnitDoclet end method testcase.createInstance
  }
  
  protected void setUp() throws Exception {
    // JUnitDoclet begin method testcase.setUp
    super.setUp();
    jmfinit = createInstance();
    // JUnitDoclet end method testcase.setUp
  }
  
  protected void tearDown() throws Exception {
    // JUnitDoclet begin method testcase.tearDown
    jmfinit = null;
    super.tearDown();
    // JUnitDoclet end method testcase.tearDown
  }
  
  public void testOpen() throws Exception {
    // JUnitDoclet begin method open
    // JUnitDoclet end method open
  }
  
  public void testControllerUpdate() throws Exception {
    // JUnitDoclet begin method controllerUpdate
    // JUnitDoclet end method controllerUpdate
  }
  
  public void testInit() throws Exception {
    // JUnitDoclet begin method init
    // JUnitDoclet end method init
  }
  
  
  
  /**
  * JUnitDoclet moves marker to this method, if there is not match
  * for them in the regenerated code and if the marker is not empty.
  * This way, no test gets lost when regenerating after renaming.
  * Method testVault is supposed to be empty.
  */
  public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
  }
  
  public static void main(String[] args) {
    // JUnitDoclet begin method testcase.main
    junit.textui.TestRunner.run(JMFInitTest.class);
    // JUnitDoclet end method testcase.main
  }
}
