package application;

import junit.framework.TestCase;
// JUnitDoclet begin import
import application.JMFRegistry;
// JUnitDoclet end import

/**
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/


public class JMFRegistryTest
// JUnitDoclet begin extends_implements
extends TestCase
// JUnitDoclet end extends_implements
{
  // JUnitDoclet begin class
  application.JMFRegistry jmfregistry = null;
  // JUnitDoclet end class
  
  public JMFRegistryTest(String name) {
    // JUnitDoclet begin method JMFRegistryTest
    super(name);
    // JUnitDoclet end method JMFRegistryTest
  }
  
  public application.JMFRegistry createInstance() throws Exception {
    // JUnitDoclet begin method testcase.createInstance
    return new application.JMFRegistry();
    // JUnitDoclet end method testcase.createInstance
  }
  
  protected void setUp() throws Exception {
    // JUnitDoclet begin method testcase.setUp
    super.setUp();
    jmfregistry = createInstance();
    // JUnitDoclet end method testcase.setUp
  }
  
  protected void tearDown() throws Exception {
    // JUnitDoclet begin method testcase.tearDown
    jmfregistry = null;
    super.tearDown();
    // JUnitDoclet end method testcase.tearDown
  }
  
  public void testWindowClosing() throws Exception {
    // JUnitDoclet begin method windowClosing
    // JUnitDoclet end method windowClosing
  }
  
  public void testMain() throws Exception {
    // JUnitDoclet begin method main
    // JUnitDoclet end method main
  }
  
  
  
  /**
  * JUnitDoclet moves marker to this method, if there is not match
  * for them in the regenerated code and if the marker is not empty.
  * This way, no test gets lost when regenerating after renaming.
  * Method testVault is supposed to be empty.
  */
  public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
  }
  
  public static void main(String[] args) {
    // JUnitDoclet begin method testcase.main
    junit.textui.TestRunner.run(JMFRegistryTest.class);
    // JUnitDoclet end method testcase.main
  }
}
