package application;

import junit.framework.TestCase;
// JUnitDoclet begin import
import application.JMStudio;
// JUnitDoclet end import

/**
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/


public class JMStudioTest
// JUnitDoclet begin extends_implements
extends TestCase
// JUnitDoclet end extends_implements
{
  // JUnitDoclet begin class
  application.JMStudio jmstudio = null;
  // JUnitDoclet end class
  
  public JMStudioTest(String name) {
    // JUnitDoclet begin method JMStudioTest
    super(name);
    // JUnitDoclet end method JMStudioTest
  }
  
  public application.JMStudio createInstance() throws Exception {
    // JUnitDoclet begin method testcase.createInstance
    return new application.JMStudio();
    // JUnitDoclet end method testcase.createInstance
  }
  
  protected void setUp() throws Exception {
    // JUnitDoclet begin method testcase.setUp
    super.setUp();
    jmstudio = createInstance();
    // JUnitDoclet end method testcase.setUp
  }
  
  protected void tearDown() throws Exception {
    // JUnitDoclet begin method testcase.tearDown
    jmstudio = null;
    super.tearDown();
    // JUnitDoclet end method testcase.tearDown
  }
  
  public void testAddNotify() throws Exception {
    // JUnitDoclet begin method addNotify
    // JUnitDoclet end method addNotify
  }
  
  public void testPack() throws Exception {
    // JUnitDoclet begin method pack
    // JUnitDoclet end method pack
  }
  
  public void testActionPerformed() throws Exception {
    // JUnitDoclet begin method actionPerformed
    // JUnitDoclet end method actionPerformed
  }
  
  public void testItemStateChanged() throws Exception {
    // JUnitDoclet begin method itemStateChanged
    // JUnitDoclet end method itemStateChanged
  }
  
  public void testWindowClosing() throws Exception {
    // JUnitDoclet begin method windowClosing
    // JUnitDoclet end method windowClosing
  }
  
  public void testWindowClosed() throws Exception {
    // JUnitDoclet begin method windowClosed
    // JUnitDoclet end method windowClosed
  }
  
  public void testUpdate() throws Exception {
    // JUnitDoclet begin method update
    // JUnitDoclet end method update
  }
  
  public void testOpen() throws Exception {
    // JUnitDoclet begin method open
    // JUnitDoclet end method open
  }
  
  public void testUpdateMenu() throws Exception {
    // JUnitDoclet begin method updateMenu
    // JUnitDoclet end method updateMenu
  }
  
  public void testMain() throws Exception {
    // JUnitDoclet begin method main
    // JUnitDoclet end method main
  }
  
  public void testCreateNewFrame() throws Exception {
    // JUnitDoclet begin method createNewFrame
    // JUnitDoclet end method createNewFrame
  }
  
  public void testCloseAll() throws Exception {
    // JUnitDoclet begin method closeAll
    // JUnitDoclet end method closeAll
  }
  
  public void testExitApllication() throws Exception {
    // JUnitDoclet begin method exitApllication
    // JUnitDoclet end method exitApllication
  }
  
  
  
  /**
  * JUnitDoclet moves marker to this method, if there is not match
  * for them in the regenerated code and if the marker is not empty.
  * This way, no test gets lost when regenerating after renaming.
  * Method testVault is supposed to be empty.
  */
  public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
  }
  
  public static void main(String[] args) {
    // JUnitDoclet begin method testcase.main
    junit.textui.TestRunner.run(JMStudioTest.class);
    // JUnitDoclet end method testcase.main
  }
}
