package application;

import junit.framework.TestCase;
// JUnitDoclet begin import
import application.PostAccessCodec;
// JUnitDoclet end import

/**
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/


public class PostAccessCodecTest
// JUnitDoclet begin extends_implements
extends TestCase
// JUnitDoclet end extends_implements
{
  // JUnitDoclet begin class
  application.PostAccessCodec postaccesscodec = null;
  // JUnitDoclet end class
  
  public PostAccessCodecTest(String name) {
    // JUnitDoclet begin method PostAccessCodecTest
    super(name);
    // JUnitDoclet end method PostAccessCodecTest
  }
  
  public application.PostAccessCodec createInstance() throws Exception {
    // JUnitDoclet begin method testcase.createInstance
    return new application.PostAccessCodec();
    // JUnitDoclet end method testcase.createInstance
  }
  
  protected void setUp() throws Exception {
    // JUnitDoclet begin method testcase.setUp
    super.setUp();
    postaccesscodec = createInstance();
    // JUnitDoclet end method testcase.setUp
  }
  
  protected void tearDown() throws Exception {
    // JUnitDoclet begin method testcase.tearDown
    postaccesscodec = null;
    super.tearDown();
    // JUnitDoclet end method testcase.tearDown
  }
  
  public void testGetName() throws Exception {
    // JUnitDoclet begin method getName
    // JUnitDoclet end method getName
  }
  
  public void testOpen() throws Exception {
    // JUnitDoclet begin method open
    // JUnitDoclet end method open
  }
  
  public void testClose() throws Exception {
    // JUnitDoclet begin method close
    // JUnitDoclet end method close
  }
  
  public void testReset() throws Exception {
    // JUnitDoclet begin method reset
    // JUnitDoclet end method reset
  }
  
  public void testGetSupportedInputFormats() throws Exception {
    // JUnitDoclet begin method getSupportedInputFormats
    // JUnitDoclet end method getSupportedInputFormats
  }
  
  public void testGetSupportedOutputFormats() throws Exception {
    // JUnitDoclet begin method getSupportedOutputFormats
    // JUnitDoclet end method getSupportedOutputFormats
  }
  
  public void testSetInputFormat() throws Exception {
    // JUnitDoclet begin method setInputFormat
    // JUnitDoclet end method setInputFormat
  }
  
  public void testSetOutputFormat() throws Exception {
    // JUnitDoclet begin method setOutputFormat
    // JUnitDoclet end method setOutputFormat
  }
  
  public void testProcess() throws Exception {
    // JUnitDoclet begin method process
    // JUnitDoclet end method process
  }
  
  public void testGetControls() throws Exception {
    // JUnitDoclet begin method getControls
    // JUnitDoclet end method getControls
  }
  
  public void testGetControl() throws Exception {
    // JUnitDoclet begin method getControl
    // JUnitDoclet end method getControl
  }
  
  
  
  /**
  * JUnitDoclet moves marker to this method, if there is not match
  * for them in the regenerated code and if the marker is not empty.
  * This way, no test gets lost when regenerating after renaming.
  * Method testVault is supposed to be empty.
  */
  public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
  }
  
  public static void main(String[] args) {
    // JUnitDoclet begin method testcase.main
    junit.textui.TestRunner.run(PostAccessCodecTest.class);
    // JUnitDoclet end method testcase.main
  }
}
