package ui.handlers;

import junit.framework.TestCase;

// JUnitDoclet begin import
// JUnitDoclet end import

/**
 * Generated by JUnitDoclet, a tool provided by ObjectFab GmbH under LGPL.
 * Please see www.junitdoclet.org, www.gnu.org and www.objectfab.de for
 * informations about the tool, the licence and the authors.
 */

public class ImagePanelHandlerTest
// JUnitDoclet begin extends_implements
        extends TestCase
// JUnitDoclet end extends_implements
{
    // JUnitDoclet begin class
    ui.handlers.ImagePanelHandler imagepanelhandler = null;

    // JUnitDoclet end class

    public ImagePanelHandlerTest(String name) {
        // JUnitDoclet begin method ImagePanelHandlerTest
        super(name);
        // JUnitDoclet end method ImagePanelHandlerTest
    }

    public ui.handlers.ImagePanelHandler createInstance() throws Exception {
        // JUnitDoclet begin method testcase.createInstance
        return new ui.handlers.ImagePanelHandler(null);
        // JUnitDoclet end method testcase.createInstance
    }

    protected void setUp() throws Exception {
        // JUnitDoclet begin method testcase.setUp
        super.setUp();
        imagepanelhandler = createInstance();
        // JUnitDoclet end method testcase.setUp
    }

    protected void tearDown() throws Exception {
        // JUnitDoclet begin method testcase.tearDown
        imagepanelhandler = null;
        super.tearDown();
        // JUnitDoclet end method testcase.tearDown
    }

    public void testChannel() throws Exception {
    // JUnitDoclet begin method channel
    // JUnitDoclet end method channel
    }

    /**
     * JUnitDoclet moves marker to this method, if there is not match for them
     * in the regenerated code and if the marker is not empty. This way, no test
     * gets lost when regenerating after renaming. Method testVault is supposed
     * to be empty.
     */
    public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
    }

    public static void main(String[] args) {
        // JUnitDoclet begin method testcase.main
        junit.textui.TestRunner.run(ImagePanelHandlerTest.class);
        // JUnitDoclet end method testcase.main
    }
}
