package util;

import junit.framework.TestCase;

// JUnitDoclet begin import
// JUnitDoclet end import

/**
 * Generated by JUnitDoclet, a tool provided by ObjectFab GmbH under LGPL.
 * Please see www.junitdoclet.org, www.gnu.org and www.objectfab.de for
 * informations about the tool, the licence and the authors.
 */

public class IntVectorTest
// JUnitDoclet begin extends_implements
        extends TestCase
// JUnitDoclet end extends_implements
{
    // JUnitDoclet begin class
    util.IntVector intvector = null;

    // JUnitDoclet end class

    public IntVectorTest(String name) {
        // JUnitDoclet begin method IntVectorTest
        super(name);
        // JUnitDoclet end method IntVectorTest
    }

    public util.IntVector createInstance() throws Exception {
        // JUnitDoclet begin method testcase.createInstance
        return new util.IntVector();
        // JUnitDoclet end method testcase.createInstance
    }

    protected void setUp() throws Exception {
        // JUnitDoclet begin method testcase.setUp
        super.setUp();
        intvector = createInstance();
        // JUnitDoclet end method testcase.setUp
    }

    protected void tearDown() throws Exception {
        // JUnitDoclet begin method testcase.tearDown
        intvector = null;
        super.tearDown();
        // JUnitDoclet end method testcase.tearDown
    }

    public void testCopyInto() throws Exception {
    // JUnitDoclet begin method copyInto
    // JUnitDoclet end method copyInto
    }

    public void testTrimToSize() throws Exception {
    // JUnitDoclet begin method trimToSize
    // JUnitDoclet end method trimToSize
    }

    public void testEnsureCapacity() throws Exception {
    // JUnitDoclet begin method ensureCapacity
    // JUnitDoclet end method ensureCapacity
    }

    public void testSetSize() throws Exception {
    // JUnitDoclet begin method setSize
    // JUnitDoclet end method setSize
    }

    public void testCapacity() throws Exception {
    // JUnitDoclet begin method capacity
    // JUnitDoclet end method capacity
    }

    public void testSize() throws Exception {
    // JUnitDoclet begin method size
    // JUnitDoclet end method size
    }

    public void testIsEmpty() throws Exception {
    // JUnitDoclet begin method isEmpty
    // JUnitDoclet end method isEmpty
    }

    public void testContains() throws Exception {
    // JUnitDoclet begin method contains
    // JUnitDoclet end method contains
    }

    public void testIndexOf() throws Exception {
    // JUnitDoclet begin method indexOf
    // JUnitDoclet end method indexOf
    }

    public void testLastIndexOf() throws Exception {
    // JUnitDoclet begin method lastIndexOf
    // JUnitDoclet end method lastIndexOf
    }

    public void testElementAt() throws Exception {
    // JUnitDoclet begin method elementAt
    // JUnitDoclet end method elementAt
    }

    public void testFirstElement() throws Exception {
    // JUnitDoclet begin method firstElement
    // JUnitDoclet end method firstElement
    }

    public void testLastElement() throws Exception {
    // JUnitDoclet begin method lastElement
    // JUnitDoclet end method lastElement
    }

    public void testSetElementAt() throws Exception {
    // JUnitDoclet begin method setElementAt
    // JUnitDoclet end method setElementAt
    }

    public void testRemoveElementAt() throws Exception {
    // JUnitDoclet begin method removeElementAt
    // JUnitDoclet end method removeElementAt
    }

    public void testInsertElementAt() throws Exception {
    // JUnitDoclet begin method insertElementAt
    // JUnitDoclet end method insertElementAt
    }

    public void testAddElement() throws Exception {
    // JUnitDoclet begin method addElement
    // JUnitDoclet end method addElement
    }

    public void testRemoveElement() throws Exception {
    // JUnitDoclet begin method removeElement
    // JUnitDoclet end method removeElement
    }

    public void testRemoveAllElements() throws Exception {
    // JUnitDoclet begin method removeAllElements
    // JUnitDoclet end method removeAllElements
    }

    public void testClone() throws Exception {
    // JUnitDoclet begin method clone
    // JUnitDoclet end method clone
    }

    public void testToArray() throws Exception {
    // JUnitDoclet begin method toArray
    // JUnitDoclet end method toArray
    }

    public void testGet() throws Exception {
    // JUnitDoclet begin method get
    // JUnitDoclet end method get
    }

    public void testSet() throws Exception {
    // JUnitDoclet begin method set
    // JUnitDoclet end method set
    }

    public void testAdd() throws Exception {
    // JUnitDoclet begin method add
    // JUnitDoclet end method add
    }

    public void testRemove() throws Exception {
    // JUnitDoclet begin method remove
    // JUnitDoclet end method remove
    }

    public void testRemoveAt() throws Exception {
    // JUnitDoclet begin method removeAt
    // JUnitDoclet end method removeAt
    }

    public void testClear() throws Exception {
    // JUnitDoclet begin method clear
    // JUnitDoclet end method clear
    }

    public void testHashCode() throws Exception {
    // JUnitDoclet begin method hashCode
    // JUnitDoclet end method hashCode
    }

    public void testEquals() throws Exception {
    // JUnitDoclet begin method equals
    // JUnitDoclet end method equals
    }

    public void testToString() throws Exception {
    // JUnitDoclet begin method toString
    // JUnitDoclet end method toString
    }

    public void testSubVector() throws Exception {
    // JUnitDoclet begin method subVector
    // JUnitDoclet end method subVector
    }

    public void testIterator() throws Exception {
    // JUnitDoclet begin method iterator
    // JUnitDoclet end method iterator
    }

    /**
     * JUnitDoclet moves marker to this method, if there is not match for them
     * in the regenerated code and if the marker is not empty. This way, no test
     * gets lost when regenerating after renaming. Method testVault is supposed
     * to be empty.
     */
    public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
    }

    public static void main(String[] args) {
        // JUnitDoclet begin method testcase.main
        junit.textui.TestRunner.run(IntVectorTest.class);
        // JUnitDoclet end method testcase.main
    }
}
