package util;

import junit.framework.TestCase;
// JUnitDoclet begin import
import util.KMeans;

// JUnitDoclet end import

/**
 * Generated by JUnitDoclet, a tool provided by ObjectFab GmbH under LGPL.
 * Please see www.junitdoclet.org, www.gnu.org and www.objectfab.de for
 * informations about the tool, the licence and the authors.
 */

public class KMeansTest
// JUnitDoclet begin extends_implements
        extends TestCase
// JUnitDoclet end extends_implements
{
    // JUnitDoclet begin class
    util.KMeans kmeans = null;

    // JUnitDoclet end class

    public KMeansTest(String name) {
        // JUnitDoclet begin method KMeansTest
        super(name);
        // JUnitDoclet end method KMeansTest
    }

    public util.KMeans createInstance() throws Exception {
        // JUnitDoclet begin method testcase.createInstance
        return null;
        // JUnitDoclet end method testcase.createInstance
    }

    protected void setUp() throws Exception {
        // JUnitDoclet begin method testcase.setUp
        super.setUp();
        kmeans = createInstance();
        // JUnitDoclet end method testcase.setUp
    }

    protected void tearDown() throws Exception {
        // JUnitDoclet begin method testcase.tearDown
        kmeans = null;
        super.tearDown();
        // JUnitDoclet end method testcase.tearDown
    }

    public void testGetBinCount() throws Exception {
    // JUnitDoclet begin method getBinCount
    // JUnitDoclet end method getBinCount
    }

    public void testGetBinSizes() throws Exception {
    // JUnitDoclet begin method getBinSizes
    // JUnitDoclet end method getBinSizes
    }

    public void testGetBinMinima() throws Exception {
    // JUnitDoclet begin method getBinMinima
    // JUnitDoclet end method getBinMinima
    }

    public void testGetBinMaxima() throws Exception {
    // JUnitDoclet begin method getBinMaxima
    // JUnitDoclet end method getBinMaxima
    }

    public void testGetBinMeans() throws Exception {
    // JUnitDoclet begin method getBinMeans
    // JUnitDoclet end method getBinMeans
    }

    public void testSortBins() throws Exception {
    // JUnitDoclet begin method sortBins
    // JUnitDoclet end method sortBins
    }

    public void testKMeans() throws Exception {
        // JUnitDoclet begin method kMeans
        double[] data = { 1, 2, 3, 4, 5, 10, 11, 12 };
        kmeans = new KMeans(data, 2);

        assertEquals(5, kmeans.getBinSizes()[0]);
        assertEquals(3, kmeans.getBinSizes()[1]);
        assertEquals(3.0, kmeans.getBinMeans()[0], 0.0);
        assertEquals(11.0, kmeans.getBinMeans()[1], 0.0);

        // JUnitDoclet end method kMeans
    }

    /**
     * JUnitDoclet moves marker to this method, if there is not match for them
     * in the regenerated code and if the marker is not empty. This way, no test
     * gets lost when regenerating after renaming. Method testVault is supposed
     * to be empty.
     */
    public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
    }

    public static void main(String[] args) {
        // JUnitDoclet begin method testcase.main
        junit.textui.TestRunner.run(KMeansTest.class);
        // JUnitDoclet end method testcase.main
    }
}
