package util;

import junit.framework.TestCase;

// JUnitDoclet begin import
// JUnitDoclet end import

/**
 * Generated by JUnitDoclet, a tool provided by ObjectFab GmbH under LGPL.
 * Please see www.junitdoclet.org, www.gnu.org and www.objectfab.de for
 * informations about the tool, the licence and the authors.
 */

public class Kmeans_oldTest
// JUnitDoclet begin extends_implements
        extends TestCase
// JUnitDoclet end extends_implements
{
    // JUnitDoclet begin class
    util.Kmeans_old kmeans_old = null;

    // JUnitDoclet end class

    public Kmeans_oldTest(String name) {
        // JUnitDoclet begin method Kmeans_oldTest
        super(name);
        // JUnitDoclet end method Kmeans_oldTest
    }

    public util.Kmeans_old createInstance() throws Exception {
        // JUnitDoclet begin method testcase.createInstance
        return null;
        // JUnitDoclet end method testcase.createInstance
    }

    protected void setUp() throws Exception {
        // JUnitDoclet begin method testcase.setUp
        super.setUp();
        kmeans_old = createInstance();
        // JUnitDoclet end method testcase.setUp
    }

    protected void tearDown() throws Exception {
        // JUnitDoclet begin method testcase.tearDown
        kmeans_old = null;
        super.tearDown();
        // JUnitDoclet end method testcase.tearDown
    }

    public void testProcess() throws Exception {
    // JUnitDoclet begin method process
    // JUnitDoclet end method process
    }

    public void testFastProcess() throws Exception {
    // JUnitDoclet begin method fastProcess
    // JUnitDoclet end method fastProcess
    }

    public void testGetMeans() throws Exception {
    // JUnitDoclet begin method getMeans
    // JUnitDoclet end method getMeans
    }

    public void testGetBorders() throws Exception {
    // JUnitDoclet begin method getBorders
    // JUnitDoclet end method getBorders
    }

    public void testGetClusterSizes() throws Exception {
    // JUnitDoclet begin method getClusterSizes
    // JUnitDoclet end method getClusterSizes
    }

    public void testGetClusterCount() throws Exception {
    // JUnitDoclet begin method getClusterCount
    // JUnitDoclet end method getClusterCount
    }

    public void testGetClusterData() throws Exception {
    // JUnitDoclet begin method getClusterData
    // JUnitDoclet end method getClusterData
    }

    public void testGetClusterNr() throws Exception {
    // JUnitDoclet begin method getClusterNr
    // JUnitDoclet end method getClusterNr
    }

    public void testInit() throws Exception {
    // JUnitDoclet begin method init
    // JUnitDoclet end method init
    }

    /**
     * JUnitDoclet moves marker to this method, if there is not match for them
     * in the regenerated code and if the marker is not empty. This way, no test
     * gets lost when regenerating after renaming. Method testVault is supposed
     * to be empty.
     */
    public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
    }

    public static void main(String[] args) {
        // JUnitDoclet begin method testcase.main
        junit.textui.TestRunner.run(Kmeans_oldTest.class);
        // JUnitDoclet end method testcase.main
    }
}
